\documentclass[12pt]{article}
\usepackage[a3paper]{geometry}
\usepackage[poster]{tcolorbox}
\usepackage{graphicx}
\usepackage{graphbox}
\usepackage[export]{adjustbox}
\usepackage{array}
\pagestyle{empty}

\begin{document}

% LOAD RELEVANT DATA AND SIMPLIFY REFERENCES
% https://kbroman.org/knitr_knutshell/pages/latex.html

<<setup,echo=FALSE>>=
out = readRDS('routput/out.rds')

lx_title <- out$my_title
lx_wtype <- unique(out$eagwl$watertype)
lx_wtypeoms <- unique(out$waterlichamenwl$typebesch)
lx_naam <- out$waterlichamenwl$OWMNAAM
lx_code <- gsub("_", "-",out$waterlichamenwl$OWL)
lx_deelgebied <- paste0(out$deelgebieden$samen,collapse=', ')
lx_karakterschets <- gsub('\r\n','',out$waterlichamenwl$Karakterschets)
lx_prov <- out$waterlichamenwl$prov
lx_gem <- out$waterlichamenwl$gem
lx_status <- out$waterlichamenwl$Status
lx_owner <- out$waterlichamenwl$Eigenaren

# text for ecologische analyse op hoofdlijnen
eah_doel <- if(!is.na(out$waterlichamenwl$Doelen)){out$waterlichamenwl$Doelen} else {'onbekend'}
eah_oorz <- if(!is.na(out$waterlichamenwl$Oorzaken)){out$waterlichamenwl$Oorzaken} else {'onbekend'}
eah_maat <- if(!is.na(out$waterlichamenwl$Maatregelen)){out$waterlichamenwl$Maatregelen} else {'onbekend'}
eah_m1 <- if(!out$d3$facet_wrap_code %in% "Macrofauna"){paste0("De slechts scorende deelmaatlat van dit kwaliteitselement is ",out$d3_deel$GHPR,".")} else {NULL} 
eah_m2 <- if(!out$d3$facet_wrap_code %in% "Macrofauna"){if(out$d3_deel$GHPR == 'Abundantie groeivormen macrofyten'){paste0("De slechts scorende indicator van deze deelmaatlat is ", out$d3_deelptn$GHPR,".")}} else {NULL}
eah_m3 <- if(!is.na(out$waterlichamenwl$Toestand)){out$waterlichamenwl$Toestand} else {NULL}
eah_message <- paste(eah_m1,eah_m2,eah_m3)

# prepare ESF tabel
pESFtab <- out$ESFtab[,c('OORDEEL','oms','piclatex')]
pESFtab$oms <- as.character(pESFtab$oms)

#location of pictures
mapEAG <- paste0('routput/',out$wlname,'/mapEAG.png')
mapDEELGEBIED <- paste0('routput/',out$wlname,'/mapDEELGEBIED.png')
mapEKR <-paste0('routput/',out$wlname,'/mapEKR.png')
@
 
% PREPARE PLOTS (https://yihui.org/knitr/options/#plots)
 
 <<eval = FALSE,label=plot_deelgebiedligging,echo=FALSE,fig.path='routput/figure/',fig.show='hide',out.height=10,out.width=10>>=
out$mapDEELGEBIED
@

<<eval = FALSE,label=plot_wlligging,echo=FALSE, fig.path='routput/figure/',fig.show = 'hide', out.height=10, out.width=10>>=
out$mapEAG
@
               
<<eval = FALSE,label=plot_ekrtoestand,echo=FALSE, fig.path='routput/figure/',fig.show = 'hide', out.height=8, out.width=13>>=
out$mapEKR
@

  \begin{tcbposter}[
    coverage = {spread, interior style={top color=white, bottom color=white}},
    poster = {showframe=false,columns=8,rows=6},
    boxes = {
    enhanced standard jigsaw,sharp corners=downhill,arc=3mm,boxrule=1mm,
    colback=white,opacityback=1,colframe=blue,
    title style={left color=blue,right color=cyan},
    fonttitle=\bfseries\scshape,
  }
  ]
  
  % Add the top row with title
  \posterbox[blankest,interior engine=path,height=2cm,halign=center,valign=center,fontupper=\bfseries\large,colupper=black]{name=title,column=1,span=8,below=top}{\resizebox{26cm}{!}{\bfseries \Sexpr{lx_naam}}}

 % add frame for beschrijving gebied en watersysteem
  \posterbox[adjusted title=Beschrijving van het gebied en watersysteem op hoofdlijnen]{
    name=gb,column=1,span=8,below=title}{
    
  % reduce size of the font
  \fontsize{9}{10.8}\selectfont
  
  % add descriptive text for this water body
Het waterlichaam \Sexpr{lx_naam} \Sexpr{lx_code} heeft watertype "\Sexpr{lx_wtypeoms} (\Sexpr{lx_wtype})" en bestaat uit de deelgebieden: \Sexpr{lx_deelgebied}. \\  \Sexpr{lx_karakterschets} Onze gebiedspartners zijn provincie \Sexpr{lx_prov} en gemeente(n) \Sexpr{lx_gem}. Het waterlichaam \Sexpr{lx_naam} heeft de status \Sexpr{lx_status} en is in eigendom van \Sexpr{lx_owner}.}
   
  % add frame for figuur Ecosysteem in beeld 
  \posterbox[adjusted title=Het ecosysteem in beeld,height = 6cm,valign=center]{name=fig1,column=1,span=2,below=gb}{
  \centering \includegraphics[height = 4cm,keepaspectratio]{\Sexpr{as.character(out$ESTnaam)}}
  }

 % add frame for figuur Ligging waterlichaam (if not saved earlier, use: routput/figure/plot_wlligging-1.pdf)
  \posterbox[adjusted title=Ligging waterlichaam,height = 6cm,valign=center]{name=fig2,column=3,span=2,below=gb}{
     \centering \includegraphics[height = 4cm,keepaspectratio]{\Sexpr{mapEAG}}
  }
  
  % add frame plot Ligging deelgebieden (if not saved earlier, use: routput/figure/plot_deelgebiedligging-1.pdf)
  \posterbox[adjusted title=Ligging deelgebieden,height = 6cm,valign=center]{name=fig3,column=5,span=2,below=gb}{
    \centering \includegraphics[height = 4cm,keepaspectratio]{\Sexpr{mapDEELGEBIED}}
  }

  % add frame for figuur EKR score huidige toestand (routput/figure/plot_ekrtoestand-1.pdf)
  \posterbox[adjusted title=Huidige toestand,height = 6cm,valign=center]{name=fig4,column=7,span=2,below=gb}{
    \centering
    \includegraphics[height = 3.5cm,keepaspectratio]{\Sexpr{mapEKR}}
  }

 %add reference methodology information in the bottom
  \posterbox[blankest,interior engine=path,height=0.6cm,fontupper=\small,colupper=black]{name=ref,column=1,span=8,above=bottom}{
  
   % reduce size of the font
  \fontsize{8}{9.6}\selectfont Auteur: laura.moria@waternet.nl. Deze factsheet is gebaseerd op de KRW toetsing aan (maatlatten 2018) uit 2019, begrenzing waterlichamen 2015-2021, hydrobiologische data 2006-2018 en conceptmaatregelen en doelen voor SGBP3 en \Sexpr{out$waterlichamenwl$Literatuurverwijzing}.
    }  
  
  % add frame for the ESF tabel plus explanation
  \posterbox[adjusted title=Ecologische Sleutelfactoren]{name=esf,column=1,span=8,above=ref}{
  
  % reduce size of the font
  \fontsize{9}{10.8}\selectfont
  
  % top strut
  \newcommand\T{\rule{0pt}{0.5cm}}
  
  % start table over the widt of the page
  \noindent\begin{tabular}{p{0.05\textwidth}m{0.9\textwidth}}
  
  \T\includegraphics[height = 0.8cm,keepaspectratio,valign=M]{\Sexpr{pESFtab$piclatex[1]}} & \Sexpr{pESFtab$oms[1]}\\
  \T\includegraphics[height = 0.8cm,keepaspectratio,valign=M]{\Sexpr{pESFtab$piclatex[2]}} & \Sexpr{pESFtab$oms[2]}\\
  \T\includegraphics[height = 0.8cm,keepaspectratio,valign=M]{\Sexpr{pESFtab$piclatex[3]}} & \Sexpr{pESFtab$oms[3]}\\
  \T\includegraphics[height = 0.8cm,keepaspectratio,valign=M]{\Sexpr{pESFtab$piclatex[4]}} & \Sexpr{pESFtab$oms[4]}\\
  \T\includegraphics[height = 0.8cm,keepaspectratio,valign=M]{\Sexpr{pESFtab$piclatex[5]}} & \Sexpr{pESFtab$oms[5]}\\
  \T\includegraphics[height = 0.8cm,keepaspectratio,valign=M]{\Sexpr{pESFtab$piclatex[6]}} & \Sexpr{pESFtab$oms[6]}\\
  \T\includegraphics[height = 0.8cm,keepaspectratio,valign=M]{\Sexpr{pESFtab$piclatex[7]}} & \Sexpr{pESFtab$oms[7]}\\
  \T\includegraphics[height = 0.8cm,keepaspectratio,valign=M]{\Sexpr{pESFtab$piclatex[8]}} & \Sexpr{pESFtab$oms[8]}\\
  \end{tabular}
  }

   % add frame for Ecologische Analyse op hoofdlijnen
  \posterbox[adjusted title=Ecologische Analyse of Hoofdlijnen]{name=analyse,column=1,span=8,between=fig1 and esf}{
  
  % reduce size of the font
  \fontsize{9}{10.8}\selectfont
  
  % add text voor de doelen
    \textbf{Doel: } \Sexpr{eah_doel} \\
    
    % huidige toestand vergeleken met doel
    \textbf{De huidige toestand: } \Sexpr{out$d3$oordeel}\\
    De toestand in \Sexpr{lx_naam} (zwarte lijnen in de figuur hierboven) is \Sexpr{out$d3$oordeel}. Het slechts scorende biologische kwaliteitselement is \Sexpr{as.character(out$d3$facet_wrap_code)}. \Sexpr{eah_message}\\

    % add oorzaken
    \textbf{Oorzaken:} \Sexpr{eah_oorz}\\
    
    % add Maatregelen op hoofdlijnen
    \textbf{Maatregelen:} \Sexpr{eah_maat}\\
  }
  
  \end{tcbposter}
  
\end{document}